services:
  couplewallet:
    image: ghcr.io/ucov/couple-wallet-pocketbase:main
    container_name: couplewallet
    restart: unless-stopped
    ports:
      - "3005:3000"
    env_file:
      - .env.local
    labels:
      - homepage.group=Finanzas
      - homepage.name=CoupleWallet
      - homepage.icon=https://wallet.unailab.top/icon-192x192.png
      - homepage.href=https://wallet.unailab.top
      - homepage.description=Gestión de finanzas en pareja

